---
name: Term-Title
version: 0.03
author:
  - 'David Golden <dagolden@cpan.org>'
abstract: Portable API to set the terminal titlebar
license: apache
resources:
  license: http://apache.org/licenses/LICENSE-2.0
requires:
  Exporter: 0
  perl: 5.004
build_requires:
  Test::More: 0.62
provides:
  Term::Title:
    file: lib/Term/Title.pm
    version: 0.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
    - t
